---
title: "Final Project"
author: "Ethan McCollister"
date: "10/17/2018"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE,
                      message = FALSE,
                      warning = FALSE)

# Load necessary packages

library(janitor)
library(knitr)
library(gganimate)
library(plotly)
library(tidyverse)
```

```{r loading data, cache = TRUE}
# Read yearly pitching data in with read_csv, using clean_names to scrub apostrophes and spaces
pitchers_2018 <- read_csv("pitchers_2018_new.csv") %>%
  clean_names()
pitchers_2017 <- read_csv("pitchers_2017_new.csv") %>%
  clean_names()
pitchers_2016 <- read_csv("pitchers_2016_new.csv") %>%
  clean_names()
pitchers_2015 <- read_csv("pitchers_2015_new.csv") %>%
  clean_names()
pitchers_2014 <- read_csv("pitchers_2014_new.csv") %>%
  clean_names()
pitchers_2013 <- read_csv("pitchers_2013_new.csv") %>%
  clean_names()
pitchers_2012 <- read_csv("pitchers_2012_new.csv") %>%  
  clean_names()
```

```{r adding_year_column, cache=TRUE}
# Added a year variable to each yearly dataset
pitchers_2018 <- pitchers_2018 %>% 
  mutate(year = "2018")
pitchers_2017 <- pitchers_2017 %>%
  mutate(year = "2017",
         
         # Needed to force screwball data to be numeric for joining. Read_csv guessed that it was a character because the entire column is NA
         v_sb_pi = as.double(v_sb_pi),
         sb_x_pi = as.double(sb_x_pi),
         sb_z_pi = as.double(sb_z_pi)) 

pitchers_2016 <- pitchers_2016 %>% 
  mutate(year = "2016",
         
         # Refer to above note
         v_sb_pi = as.double(v_sb_pi),
         sb_x_pi = as.double(sb_x_pi),
         sb_z_pi = as.double(sb_z_pi))

pitchers_2015 <- pitchers_2015 %>% 
  mutate(year = "2015",
         
         # Refer to above note
         v_sb_pi = as.double(v_sb_pi),
         sb_x_pi = as.double(sb_x_pi),
         sb_z_pi = as.double(sb_z_pi))
pitchers_2014 <- pitchers_2014 %>% 
  mutate(year = "2014")
pitchers_2013 <- pitchers_2013 %>% 
  mutate(year = "2013")
pitchers_2012 <- pitchers_2012 %>% 
  mutate(year = "2012")
```

## Creating Master Dataframes
```{r creating_masters}
# Used full join to stack datasets, pulling all data into a single df

pitchers_all <- pitchers_2018 %>%
  full_join(pitchers_2017) %>% 
  full_join(pitchers_2016) %>%
  full_join(pitchers_2015) %>% 
  full_join(pitchers_2014) %>%
  full_join(pitchers_2013) %>%
  full_join(pitchers_2012)
```

```{r write csv}
# created a .csv file of the master raw dataframe for recreating purposes
write_csv(pitchers_all, "pitchers_all.csv")
```

```{r}
# The following code tests a new variable "type", which describes whether a pitcher is a reliever or a starter. This is necessary as I expect relievers to have systematically higher velocity given their (generally) reduced usage. The following also creates a table just to see which pitchers are left out of the binary categorization, as they have equal numbers of relief innings and starting innings. I made the decision that this was an appropriate procedure

pitchers_all %>%
  mutate(type = case_when(start_ip > relief_ip ~ "SP",
                          start_ip < relief_ip ~ "RP",
                          is.na(start_ip) ~ "RP",
                          is.na(relief_ip) ~ "SP",
                          TRUE ~ "other")) %>%
  filter(type == "other") %>%
  select(name, start_ip, relief_ip, year, type)
```


```{r tidying data}
# Creates a new dataset of the tidied data
pitchers_tidy <- pitchers_all %>%
  
  # Code copied from above chunk
  mutate(type = case_when(start_ip > relief_ip ~ "SP",
                          start_ip < relief_ip ~ "RP",
                          is.na(start_ip) ~ "RP",
                          is.na(relief_ip) ~ "SP",
                          TRUE ~ "other"),
         
         # Use mutate and stringr to remove % sign from all of the pitch usage columns, then mutate again to cast the data, which is still structured as "character" into "numeric"
         fa_pct = str_remove_all(fa_percent_pi, " %"),
         fa_pct = as.numeric(fa_pct),
         fc_pct = str_remove_all(fc_percent_pi, " %"),
         fc_pct = as.numeric(fc_pct),
         fs_pct = str_remove_all(fs_percent_pi, " %"),
         fs_pct = as.numeric(fs_pct),
         si_pct = str_remove_all(si_percent_pi, " %"),
         si_pct = as.numeric(si_pct),
         sl_pct = str_remove_all(sl_percent_pi, " %"),
         sl_pct = as.numeric(sl_pct),
         cu_pct = str_remove_all(cu_percent_pi, " %"),
         cu_pct = as.numeric(cu_pct),
         ch_pct = str_remove_all(ch_percent_pi, " %"),
         ch_pct = as.numeric(ch_pct),
         cs_pct = str_remove_all(cs_percent_pi, " %"),
         cs_pct = as.numeric(cs_pct),
         sb_pct = str_remove_all(sb_percent_pi, " %"),
         sb_pct = as.numeric(sb_pct),
         kn_pct = str_remove_all(kn_percent_pi, " %"),
         kn_pct = as.numeric(kn_pct),
         
         # Decided to also force the year data into numeric for graphing purposes
         year = as.numeric(year),
         sw_str_pct = str_remove_all(sw_str_percent, " %"),
         sw_str_pct = as.numeric(sw_str_pct),
         
         # Created a strike percent column out of the appropriate raw counts
         str_pct = strikes / pitches * 100,
         
         hand = case_when(cu_x_pi > 0 | sl_x_pi > 0 | fa_x_pi < 0 ~ "RH",
                          cu_x_pi < 0 | sl_x_pi < 0 | fa_x_pi > 0 ~ "LH",
                          name %in% c("Tony Watson", "Francisco Liriano") ~ "LH",
                          name == "Mariano Rivera" ~ "RH")) %>%
  
  # Selected out necessary variables
 select(name:relief_ip,
        type,
        hand,
        war,
        sw_str_pct,
        str_pct,
        k_9:year,
        fa_pct:kn_pct,
        v_ch_pi:sl_z_pi) 
```
```{r }
# Create final, shiny ready data set
# This chunk took the data structure from a row showing all pitch data for all pitches per player per year to each row showing all pitch data for ONE pitch per player per year.

pitchers_shiny <- pitchers_tidy %>%
  
  # Gather all pitch data into narrow format with a variable and a value column
  gather(key = pitch, value = value, fa_pct:sl_z_pi, na.rm = TRUE) %>%
  
  # Used mutate and stringr functions to create a column of variable types 
  mutate(measure = case_when(str_detect(pitch, "pct") == TRUE ~ "Percent",
                             str_detect(pitch, "v_") == TRUE ~ "Velocity",
                             str_detect(pitch, "_x_") == TRUE ~ "Movement_X",
                             str_detect(pitch, "_z_") == TRUE ~ "Movement_Y")) %>%
  
  # Spread data back out by newly created measures
  spread(key = measure, value = value) %>% 
  
  # Rewrote pitch variable to show pitch type, now showing pitch type and pitch measure in separate cols. However, the data was full of NAs as each row showed one pitch measure for one pitch type
  mutate(pitch = case_when(pitch %in% c("fa_pct",
                                        "v_fa_pi",
                                        "fa_x_pi",
                                        "fa_z_pi") ~ "fastball",
                           pitch %in% c("ch_pct",
                                        "v_ch_pi",
                                        "ch_x_pi",
                                        "ch_z_pi") ~ "changeup",
                           pitch %in% c("cu_pct",
                                        "v_cu_pi",
                                        "cu_x_pi",
                                        "cu_z_pi") ~ "curveball",
                           pitch %in% c("sl_pct",
                                        "v_sl_pi",
                                        "sl_x_pi",
                                        "sl_z_pi") ~ "slider",
                           pitch %in% c("fc_pct",
                                        "v_fc_pi",
                                        "fc_x_pi",
                                        "fc_z_pi") ~ "cutter",
                           pitch %in% c("si_pct",
                                        "v_si_pi",
                                        "si_x_pi",
                                        "si_z_pi") ~ "sinker",
                           pitch %in% c("fs_pct",
                                        "v_fs_pi",
                                        "fs_x_pi",
                                        "fs_z_pi") ~ "splitter",
                           pitch %in% c("cs_pct",
                                        "v_cs_pi",
                                        "cs_x_pi",
                                        "cs_z_pi") ~ "slow_curve",
                           pitch %in% c("kn_pct",
                                        "v_kn_pi",
                                        "kn_x_pi",
                                        "kn_z_pi") ~ "knuckleball",
                           pitch %in% c("sb_pct",
                                        "v_sb_pi",
                                        "sb_x_pi",
                                        "sb_z_pi") ~ "screwball",
                           TRUE ~ "OTHER")) %>%
  
  # Verified that there were no "OTHER" points present in the data with following command
  # filter(pitch == "OTHER") %>%
  
  # Again gathered the data but with na.rm = TRUE to get rid of all the pitch type/pitch measure combinations that didn't exist
  gather(key = measure, value, Movement_X:Velocity, na.rm = TRUE) %>%
  
  # Spread data back once more to reach desired format
  spread(measure, value) 
```

```{r write csv}
# Wrote .csv file to bring into shiny app
write_csv(pitchers_shiny, "pitchers_shiny.csv")
```

```{r create dataframe needed for visualising movement}
movement_shiny <- pitchers_shiny %>%
  
  filter(type != "other") %>%
  group_by(type, hand, pitch) %>%
  summarize(Movement_X = mean(Movement_X),
            Movement_Y = mean(Movement_Y),
            Velocity = mean(Velocity)) %>% 
  mutate(Name = case_when(type == "RP" ~ "Average Reliever",
                          type == "SP" ~ "Average Starter"),
         frame = 2) %>% 
  select(Name, everything())

movement_origin <- data_frame(
  Name = c("Origin1","Origin2"),
  type = c("Origin","Origin"),
  hand = c("Origin", "Origin"),
  pitch = c("Origin", "Origin"),
  Movement_X = c(0, 0),
  Movement_Y = c(0, 0),
  frame = c(1, 1))

 movement_shiny <- movement_shiny %>% 
  full_join(movement_origin)
 
 # I opted to make this a .rds instead of a .csv as this file as no value outside of the shiny app
 # Conversely, the previously written .csv files are interesting in their own right
 write_rds(movement_shiny, "movement_shiny.rds")
```
```{r}
movement_test <- pitchers_shiny %>% 
  filter(name == "Chris Sale",
         pitch == "slider",
         year == 2018) %>% 
  mutate(frame = 2)

if (movement_test$type == "SP" & movement_test$hand == "RH") {
  x <- movement_shiny %>%
  filter(pitch %in% c("slider", "Origin"),
         type %in% c("SP", "Origin"),
         hand %in% c("RH", "Origin")) %>%
  rename(name = Name)
} else if (movement_test$type == "SP" & movement_test$hand == "LH"){
  x <- movement_shiny %>%
  filter(pitch %in% c("slider", "Origin"),
         type %in% c("SP", "Origin"),
         hand %in% c("LH", "Origin")) %>%
  rename(name = Name) 
} else if (movement_test$type == "RP" & movement_test$hand == "RH"){
  x <- movement_shiny %>%
  filter(pitch %in% c("slider", "Origin"),
         type %in% c("RP", "Origin"),
         hand %in% c("RH", "Origin")) %>%
  rename(name = Name) 
} else if (movement_test$type == "RP" & movement_test$hand == "LH"){
  x <- movement_shiny %>%
  filter(pitch %in% c("slider", "Origin"),
         type %in% c("RP", "Origin"),
         hand %in% c("LH", "Origin")) %>%
  rename(name = Name) 
}

mvmt_plot_test <- movement_test %>% 
  full_join(x)


test_plot <- mvmt_plot_test %>%
  ggplot(aes(x = Movement_X, y = Movement_Y, frame = frame, col = name)) + 
  geom_point() +
  scale_y_continuous(limits = c(-15, 15)) +
  scale_x_continuous(limits = c(-15, 15))


```
```{r}
ggplotly(test_plot)
```


```{r}
movement_shiny %>%
  filter(pitch %in% c("slider", "Origin"),
         type %in% c("SP", "Origin")) %>% 
  rename(name = Name)
```


